spring:
  profiles:
    active: jdbc
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/logistics?useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456
    
    
  datasource2:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/logistics1?useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456
    


  datasourceinterceptor:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/logistics?useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

elastic:
  clusterName: wali
  ip1: 127.0.0.1
  port: 9300
